Repository PowerShell/PowerShellEditorServices, pull requests merged in 2019-10, with the labels that each got.

#1044 Fix UNC intellisense backslash
  src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Labels: Backport-Legacy

#1055 Update .Net Core SDK from 2.1.801 to 2.1.802 (latest patch)
  global.json
Labels: Area-Build & Release

#1072 Override PSRL ReadKey on Windows as well
  src/PowerShellEditorServices/Services/PowerShellContext/Console/ConsoleProxy.cs
  src/PowerShellEditorServices/Services/PowerShellContext/Session/PSReadLinePromptContext.cs
Labels: Area-ReadLine, Issue-Bug

#1064 New colors supported by PS7
  src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHost.cs
  src/PowerShellEditorServices/Services/PowerShellContext/Session/Host/EditorServicesPSHostUserInterface.cs
Labels: Backport-Legacy
