Repository PowerShell/PowerShellEditorServices, pull requests merged in 2019-11, with the labels that each got.

#1097 Fixes no prompt showing up
  src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
Labels: Area-Debugging, Area-ReadLine

#1101 Add PSAvoidAssignmentToAutomaticVariable to the default set of PSSA rules
  src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
Labels: Backport-Legacy

#1107 Protect against no RootUri (no open workspace)
  src/PowerShellEditorServices/Server/PsesLanguageServer.cs
Labels: Area-Startup, Issue-Bug, Preview Extension
