Repository PowerShell/PowerShellEditorServices, pull requests merged in 2019-03, with the labels that each got.

#876 Temporarily disable deemphasized stack frames to fix VSCode-powershell issue 1750
  src/PowerShellEditorServices/Debugging/StackFrameDetails.cs
Labels: Backport-Legacy, Triage

#871 Support -CustomPipeName
  src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
  src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
Labels: Backport-Legacy, Triage

#872 Fix unable to open files in problems/peek windows issue
  src/PowerShellEditorServices.Host/CodeLens/CodeLensFeature.cs
  src/PowerShellEditorServices.Host/CodeLens/PesterCodeLensProvider.cs
  src/PowerShellEditorServices.Host/CodeLens/ReferencesCodeLensProvider.cs
  src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
  src/PowerShellEditorServices/Workspace/ScriptFile.cs
  src/PowerShellEditorServices/Workspace/Workspace.cs
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
  test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Labels: Backport-Legacy, Triage

#875 Add attach to local runspace.
  src/PowerShellEditorServices.Protocol/DebugAdapter/AttachRequest.cs
  src/PowerShellEditorServices.Protocol/LanguageServer/GetRunspaceRequest.cs
  src/PowerShellEditorServices.Protocol/Server/DebugAdapter.cs
  src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
Labels: Triage

#874 Use public InternalHost from origin runspace
  module/PowerShellEditorServices/PowerShellEditorServices.psm1
  src/PowerShellEditorServices.Host/EditorServicesHost.cs
  src/PowerShellEditorServices/Console/ConsoleProxy.cs
  src/PowerShellEditorServices/Console/ConsoleReadLine.cs
  src/PowerShellEditorServices/Console/IConsoleOperations.cs
  src/PowerShellEditorServices/Console/UnixConsoleOperations.cs
  src/PowerShellEditorServices/Console/WindowsConsoleOperations.cs
  src/PowerShellEditorServices/PowerShellEditorServices.csproj
  src/PowerShellEditorServices/Session/Host/EditorServicesPSHostUserInterface.cs
  src/PowerShellEditorServices/Session/Host/TerminalPSHostRawUserInterface.cs
  src/PowerShellEditorServices/Session/Host/TerminalPSHostUserInterface.cs
Labels: Triage

#888 Add new ParseError level to ScriptFileMarkerLevel and only have it send parse errors
  src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs
  src/PowerShellEditorServices/Analysis/AnalysisService.cs
  src/PowerShellEditorServices/Workspace/ScriptFile.cs
  src/PowerShellEditorServices/Workspace/ScriptFileMarker.cs
  test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Labels: Backport-Legacy

#895 Add warning to parameter validation set
  module/PowerShellEditorServices/Start-EditorServices.ps1
Labels: Backport-Legacy
