Repository PowerShell/PowerShellEditorServices, pull requests merged in 2021-12, with the labels that each got.

#1647 Create `$psEditor` as a constant
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
Labels: Issue-Bug, Area-Engine

#1635 Re-enable `DebugServiceTests` suite
  PowerShellEditorServices.build.ps1
  src/PowerShellEditorServices/Services/DebugAdapter/DebugEventHandlerService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/DebugStateService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/DebuggerStoppedEventArgs.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/SetVariableHandler.cs
  src/PowerShellEditorServices/Services/Extension/EditorOperationsService.cs
  src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
  src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
  src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
  test/PowerShellEditorServices.Test/PsesHostFactory.cs
Labels: Issue-Bug, Area-Debugging

#1648 Release `v3.0.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1650 Release `v2.5.3`
  CHANGELOG.md
Labels: Ignore

#1636 Add magic value formatting for variable booleans
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
  test/PowerShellEditorServices.Test.Shared/Debugging/VariableTest.ps1
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Labels: Issue-Enhancement, Area-Debugging
