Repository PowerShell/PowerShellEditorServices, pull requests merged in 2021-04, with the labels that each got.

#1454 Update CHANGELOG for v2.4.0-preview.1
  CHANGELOG.md
Labels: Area-Build & Release, Issue-Enhancement

#1456 Fix version in module definition file
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Area-Build & Release, Issue-Bug

#1460 Bump OmniSharp package to `0.19.2-beta0001`
  src/PowerShellEditorServices/Extensions/Api/EditorExtensionServiceProvider.cs
  src/PowerShellEditorServices/PowerShellEditorServices.csproj
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ThreadsHandler.cs
  test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
  test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Labels: Area-Debugging, Area-Language Server, Issue-Bug

#1461 Release `v2.4.1-preview.1`
  .vsts-ci/azure-pipelines-release.yml
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Area-Build & Release, Ignore

#1464 Create `codeql-analysis.yml`
  .github/workflows/codeql-analysis.yml
Labels: Area-Build & Release, Issue-Enhancement

#1467 Make code more explicit
  src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
  src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
  src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
Labels: Area-Engine, Issue-Enhancement

#1468 Upgrade to GitHub-Native Dependabot
  .dependabot/config.yml
  .github/dependabot.yml
Labels: Area-Build & Release, Ignore, Issue-Bug

#1471 Remove deprecated badges
  .github/dependabot.yml
  README.md
Labels: Area-Documentation, Ignore
