Repository PowerShell/PowerShellEditorServices, pull requests merged in 2021-05, with the labels that each got.

#1473 Delete deprecated files
  scripts/AddCopyrightHeaders.ps1
  scripts/BuildDocs.ps1
  scripts/FetchLatestBuild.ps1
  scripts/PackageSignedBinaries.ps1
  scripts/PublishPackages.ps1
  scripts/ReleaseProcess.md
  src/PowerShellEditorServices/.vscode/launch.json
  tools/PsesLogAnalyzer/.vscode/launch.json
  tools/PsesLogAnalyzer/Analyze.ps1
  tools/PsesLogAnalyzer/Parse-PsesLog.ps1
  tools/PsesLogAnalyzer/PsesLogAnalyzer.format.ps1xml
  tools/PsesLogAnalyzer/PsesLogAnalyzer.psd1
  tools/PsesLogAnalyzer/PsesLogAnalyzer.psm1
  tools/PsesLogAnalyzer/Types.ps1
  tools/releaseBuild/FileCatalogSigning.xml
Labels: Ignore

#1474 Add more logging and internal documentation
  src/PowerShellEditorServices.Hosting/BuildInfo.cs
  src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
  src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
  src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
  src/PowerShellEditorServices/Hosting/EditorServicesLoading.cs
  src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
  src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
  src/PowerShellEditorServices/Logging/LoggerExtensions.cs
  src/PowerShellEditorServices/Logging/PsesTelemetryEvent.cs
  src/PowerShellEditorServices/Server/PsesDebugServer.cs
  src/PowerShellEditorServices/Server/PsesLanguageServer.cs
  src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
  src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs
  src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
Labels: Area-Logging, Issue-Enhancement

#1481 Bump OmniSharp to `v0.19.2-beta0002`
  src/PowerShellEditorServices/PowerShellEditorServices.csproj
  test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
  test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Labels: Area-Language Server, Area-Startup, Issue-Bug

#1483 Release `v2.4.2-preview.1`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1484 Fix unintentional module import
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Labels: Area-IntelliSense, Issue-Bug

#1491 Bump OmniSharp to `v0.19.2`
  src/PowerShellEditorServices/PowerShellEditorServices.csproj
  test/PowerShellEditorServices.Test.E2E/PowerShellEditorServices.Test.E2E.csproj
  test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Labels: dependencies
