Repository PowerShell/PowerShellEditorServices, pull requests merged in 2021-11, with the labels that each got.

#1612 Remove Rob from Dependabot reviewers and Code Owners
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: Ignore

#1606 Add `LengthInBufferCells` back to `EditorServicesConsolePSHostRawUserInterface`
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostRawUserInterface.cs
Labels: Issue-Bug, Area-Integrated Console

#1611 Improve PowerShell command and argument escaping
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
  src/PowerShellEditorServices/Utility/ArgumentUtils.cs
  src/PowerShellEditorServices/Utility/PathUtils.cs
  src/PowerShellEditorServices/Utility/StringEscaping.cs
  test/PowerShellEditorServices.Test.Shared/scriptassets/[Truly] b&d `N$(){}me_4_script.ps1
  test/PowerShellEditorServices.Test/Session/PathEscapingTests.cs
  test/PowerShellEditorServices.Test/Utility/ArgumentEscapingTests.cs
Labels: Issue-Bug, Area-Debugging

#1618 Release `v3.0.1`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1626 Remove Windows Server 2016 from CI
  .vsts-ci/azure-pipelines-ci.yml
Labels: Ignore

#1628 Fix build for Apple M1 when running PowerShell 7.2 (arm64)
  PowerShellEditorServices.build.ps1
  test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Labels: Ignore

#1630 Improve debugger's variable population mechanism
  PowerShellEditorServices.Common.props
  src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/StackFrameDetails.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableContainerDetails.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/VariableDetails.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
Labels: Issue-Bug, Area-Debugging

#1631 Add Justin Grote as maintainer
  README.md
Labels: Issue-Enhancement, Area-Documentation

#1632 Release `v3.0.2`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1638 Fix `BundledModulePath` and PSReadLine loading (redux)
  src/PowerShellEditorServices/Services/PowerShell/Console/PSReadLineProxy.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Startup
