Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-10, with the labels that each got.

#1932 Add example of starting PSES in a script to readme
  README.md
Labels: Issue-Enhancement, Area-Documentation

#1933 Fix release build
  .vsts-ci/templates/ci-general.yml
Labels: Issue-Bug, Area-Build & Release

#1936 Fix regression around `OnIdle` handler
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  test/PowerShellEditorServices.Test.Shared/Profile/Test.PowerShellEditorServices_profile.ps1
  test/PowerShellEditorServices.Test/PsesHostFactory.cs
  test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Labels: Issue-Bug, Area-Engine

#1935 Catch exceptions within completion handler
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
  test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Labels: Issue-Bug, Area-IntelliSense

#1937 Release `v3.6.0`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1938 Remove `/p:UseSharedCompilation=false` injection
  PowerShellEditorServices.build.ps1
Labels: Ignore
