Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-05, with the labels that each got.

#1784 Do not exit from `DebuggerStop` unless resuming
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1785 Add `IHostUISupportsMultipleChoiceSelection` implementation
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
Labels: Issue-Enhancement, Area-Integrated Console

#1786 Release `v3.3.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1787 Bump PSReadLine to `v2.2.5`
  modules.json
Labels: dependencies

#1788 Release `v3.3.4`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1791 Send `sendKeyPress` event across DAP for temporary integrated consoles
  src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
  src/PowerShellEditorServices/Server/PsesDebugServer.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1792 Release `v3.3.5`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1801 Re-enable stdio clients by fixing initialization sequence
  src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
  src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
  src/PowerShellEditorServices/Server/PsesDebugServer.cs
  src/PowerShellEditorServices/Server/PsesLanguageServer.cs
  src/PowerShellEditorServices/Server/PsesServiceCollectionExtensions.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/NullPSHostRawUI.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/NullPSHostUI.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/DocumentHighlightHandler.cs
  src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteAttributeValue.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandFromModule.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandInFile.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteNamespace.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteTypeName.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteVariableInFile.cs
Labels: Issue-Bug, Area-Language Server

#1803 Fix execution of debug prompt commands
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
Labels: Issue-Bug, Area-Debugging

#1804 Wrap untitled script with newlines
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
Labels: Issue-Bug, Area-Debugging

#1802 Set `EnableProfileLoading` default to `true`
  src/PowerShellEditorServices/Server/PsesLanguageServer.cs
  test/PowerShellEditorServices.Test.E2E/LSPTestsFixures.cs
Labels: Issue-Bug, Area-Integrated Console

#1805 Release `v3.4.0`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1807 Fix startup bug when zero profiles are present
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
  src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
Labels: Issue-Bug, Area-Startup

#1808 Release `v3.4.1`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1809 Additional IntelliSense fixes and ToolTip overhaul
  src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  src/PowerShellEditorServices/Utility/Extensions.cs
  src/PowerShellEditorServices/Utility/FormatUtils.cs
  test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
Labels: Issue-Enhancement, Area-IntelliSense

#1811 Release `v3.4.2`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore
