Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-06, with the labels that each got.

#1814 Fix error when piping `IFilePosition` to `ConvertTo-ScriptExtent`
  module/PowerShellEditorServices/Commands/Public/ConvertTo-ScriptExtent.ps1
  module/PowerShellEditorServices/Commands/Public/Set-ScriptExtent.ps1
  src/PowerShellEditorServices/Extensions/EditorFileRanges.cs
Labels: Issue-Bug, Area-API

#1819 Remove bad UX of commit characters for paths
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
Labels: Issue-Bug, Area-IntelliSense

#1818 Exit debugger stop early if cause is PSE
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1820 Add Emacs regression tests for PSES
  .github/workflows/emacs-test.yml
  test/emacs-test.el
Labels: Issue-Enhancement, Area-Build & Release

#1821 Add regression test for no defined profiles
  test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Labels: Issue-Enhancement, Area-Startup

#1824 Configure Dependabot to update GitHub Actions
  .github/dependabot.yml
Labels: Ignore

#1827 Release `v3.4.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1830 Add regression test for untitled scripts in Windows PowerShell
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
  src/PowerShellEditorServices/Services/Symbols/SymbolsService.cs
  src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
  src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs
  src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
  test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs
  test/PowerShellEditorServices.Test.E2E/DebugAdapterProtocolMessageTests.cs
  test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
  test/PowerShellEditorServices.Test.E2E/Processes/PsesStdioProcess.cs
  test/PowerShellEditorServices.Test/Language/SymbolsServiceTests.cs
  test/PowerShellEditorServices.Test/Session/ScriptFileTests.cs
Labels: Issue-Enhancement, Area-Test

#1832 Improve `$PROFILE` variable and profile loading test
  test/PowerShellEditorServices.Test.Shared/Profile/Test.PowerShellEditorServices_profile.ps1
  test/PowerShellEditorServices.Test/Session/PsesInternalHostTests.cs
Labels: Issue-Enhancement, Area-Test

#1833 Add readme about `ReadKey` workarounds
  src/PowerShellEditorServices/Services/PowerShell/Console/README.md
Labels: Issue-Enhancement, Area-Documentation

#1834 Update processor architecture check in build script
  PowerShellEditorServices.build.ps1
Labels: Ignore

#1839 Fix logic checking for untitled or raw scripts
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
Labels: Issue-Bug, Area-Debugging

#1840 Release `v3.4.4`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1841 Add command to PSReadLine history before cancellation
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1843 Find/replace of `master` to `main` for branch rename
  .github/workflows/codeql-analysis.yml
  .github/workflows/emacs-test.yml
  .vsts-ci/misc-analysis.yml
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  README.md
  module/PowerShellEditorServices.VSCode/PowerShellEditorServices.VSCode.psd1
  module/PowerShellEditorServices/Commands/PowerShellEditorServices.Commands.psd1
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
  module/PowerShellEditorServices/Start-EditorServices.ps1
  module/docs/ConvertFrom-ScriptExtent.md
  module/docs/ConvertTo-ScriptExtent.md
  module/docs/Find-Ast.md
  module/docs/Get-Token.md
  module/docs/Import-EditorCommand.md
  module/docs/Join-ScriptExtent.md
  module/docs/Out-CurrentFile.md
  module/docs/Register-EditorCommand.md
  module/docs/Set-ScriptExtent.md
  module/docs/Test-ScriptExtent.md
  module/docs/Unregister-EditorCommand.md
Labels: Issue-Enhancement, Area-Documentation

#1845 Update PSReadLine to v2.2.6
  modules.json
Labels: Issue-Enhancement, Area-ReadLine
