Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-02, with the labels that each got.

#1690 Display prompt after `F8` finishes
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebugEvaluateHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1692 Fix printing of command with F5
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Ignore

#1696 Release `v3.1.2`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1698 Remove temporary `dotnet publish` workaround
  src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
Labels: Ignore

#1693 Replace superfluous `Default` member with default values
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/LegacyReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Debugging/DscBreakpointCapability.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousDelegateTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
  src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
Labels: Ignore

#1700 Clean up LSP message tests
  test/PowerShellEditorServices.Test.E2E/DebugAdapterClientExtensions.cs
  test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Labels: Ignore

#1705 Add SBOM template
  .vsts-ci/templates/ci-general.yml
  .vsts-ci/templates/release-general.yml
Labels: Ignore

#1703 Use `static readonly` for default `ExecutionOptions`
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousDelegateTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousTask.cs
Labels: Issue-Enhancement, Area-Debugging

#1704 Avoid recording debugger commands in the history
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Labels: Issue-Bug, Area-Debugging

#1710 Handle edge case where `prompt` is undefined
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1712 Avoid stopping the debugger when canceling other tasks in a debug session
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1711 Redirect `EditorServicesConsolePSHost.PrivateData` to `_internalHost`
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1714 Release `v3.1.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1716 Use global `dotnet` and update build dependencies
  .vsts-ci/azure-pipelines-release.yml
  .vsts-ci/templates/ci-general.yml
  PowerShellEditorServices.build.ps1
  tools/azurePipelinesBuild.ps1
Labels: Ignore

#1718 Return a code action for each diagnostic record
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
Labels: Issue-Bug, Area-Script Analysis

#1723 Update PSReadLine to 2.2.2
  modules.json
Labels: Issue-Enhancement, Area-ReadLine

#1719 Reset progress messages at end of REPL
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1724 Re-enable line breakpoints for untitled scripts
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
  src/PowerShellEditorServices/Utility/PSCommandExtensions.cs
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Labels: Issue-Enhancement, Area-Debugging

#1726 Avoid error when `exclude` entry is a clause
  src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
  src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Labels: Issue-Bug, Area-Startup

#1725 Fix editor commands to interrupt current prompt
  src/PowerShellEditorServices/Extensions/Api/ExtensionCommandService.cs
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/Extension/Handlers/InvokeExtensionCommandHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
Labels: Issue-Bug, Area-Engine

#1727 Release `v3.1.4`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1732 Redirect `PSHost.Notify*Application` methods
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console

#1734 Finish redirection of `$Host.PrivateData`
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Integrated Console
