Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-09, with the labels that each got.

#1909 Update link to emacs-lsp lsp-pwsh plugin
  README.md
Labels: Ignore

#1914 Add regression tests for F5 and F8 saving to history
  src/PowerShellEditorServices/Services/PowerShell/Console/ReadLineProvider.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs
Labels: Issue-Enhancement, Area-Test

#1915 Change CI build script to only build
  .vsts-ci/templates/ci-general.yml
  PowerShellEditorServices.build.ps1
  tools/azurePipelinesBuild.ps1
Labels: Ignore

#1918 Created a nested PowerShell for the top-level loop
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Startup

#1922 Fix Emacs unit test
  test/emacs-test.el
Labels: Ignore

#1921 Update Andy's name
  README.md
  test/emacs-test.el
Labels: Ignore

#1923 Release `v3.5.2`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1925 Release `v3.5.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1916 Upgrade PSScriptAnalyzer to 1.21.0
  modules.json
  src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Labels: Issue-Enhancement, Area-Code Formatting

#1928 Generalize the execution busy status to all PowerShell tasks
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Enhancement, Area-Engine

#1929 Release `v3.5.4`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore
