Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-03, with the labels that each got.

#1735 Remove `PackageManagement` module update prompt
  src/PowerShellEditorServices/Services/PowerShell/Handlers/GetVersionHandler.cs
  src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
  src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
Labels: Issue-Bug, Area-Startup

#1738 Improve completion logic
  src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
  src/PowerShellEditorServices/Services/TextDocument/CompletionResults.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteAttributeValue.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandFromModule.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteCommandInFile.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteFilePath.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteNamespace.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteTypeName.cs
  test/PowerShellEditorServices.Test.Shared/Completion/CompleteVariableInFile.cs
  test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
Labels: Issue-Enhancement, Area-IntelliSense

#1739 Release `v3.1.5`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1740 Finish use of ABC instead of interface TODOs
  src/PowerShellEditorServices/Server/PsesDebugServer.cs
  src/PowerShellEditorServices/Server/PsesLanguageServer.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/DebuggerActionHandlers.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeLensHandlers.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
Labels: Ignore

#1747 Release `v3.1.6`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1749 Correctly map `SuggestedCorrection` to `MarkerCorrection`
  src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CodeActionHandler.cs
  src/PowerShellEditorServices/Services/TextDocument/ScriptFileMarker.cs
Labels: Issue-Bug, Area-Script Analysis
