Repository PowerShell/PowerShellEditorServices, pull requests merged in 2022-04, with the labels that each got.

#1751 Re-workaround uncancellable `Console.ReadKey`
  .vsts-ci/templates/release-general.yml
  Third Party Notices.txt
  src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
  src/PowerShellEditorServices/PowerShellEditorServices.csproj
  src/PowerShellEditorServices/Services/PowerShell/Console/ConsoleProxy.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/IConsoleOperations.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/IReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/LegacyReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/PsrlReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/TerminalReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/UnixConsoleOperations.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/WindowsConsoleOperations.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostRawUserInterface.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/EditorServicesConsolePSHostUserInterface.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  test/PowerShellEditorServices.Test/Language/CompletionHandlerTests.cs
Labels: Issue-Bug, Area-ReadLine

#1753 Release `v3.2.0`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1752 Fix attach to process debugging
  PowerShellEditorServices.build.ps1
  src/PowerShellEditorServices/Server/PsesDebugServer.cs
  src/PowerShellEditorServices/Services/DebugAdapter/BreakpointService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/DebugService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellContextFrame.cs
  src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellFrameType.cs
  src/PowerShellEditorServices/Services/PowerShell/Debugging/IPowerShellDebugContext.cs
  src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellDebugDisplay.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/PowerShellExtensions.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/RunspaceExtensions.cs
  test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Labels: Issue-Bug, Area-Debugging

#1760 Release `v3.3.0`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1762 Fix prompt spam and general debugger reliability improvements
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1764 Fix formatting handlers and PSScriptAnalyzer loading
  src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/FormattingHandlers.cs
Labels: Issue-Bug, Area-Code Formatting

#1766 Bump `net461` to `net462` due to upcoming end of support
  PowerShellEditorServices.build.ps1
  src/PowerShellEditorServices.Hosting/PowerShellEditorServices.Hosting.csproj
  test/PowerShellEditorServices.Test.Shared/TestUtilities/TestUtilities.cs
  test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj
Labels: Issue-Bug, Area-Build & Release

#1759 Enable IDE0005 (unneccessary using statements) as error
  .editorconfig
  PowerShellEditorServices.Common.props
  src/PowerShellEditorServices.Hosting/Configuration/HostLogger.cs
  src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
  src/PowerShellEditorServices/Extensions/Api/EditorExtensionServiceProvider.cs
  src/PowerShellEditorServices/Extensions/EditorObject.cs
  src/PowerShellEditorServices/Extensions/FileContext.cs
  src/PowerShellEditorServices/Hosting/EditorServicesServerFactory.cs
  src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
  src/PowerShellEditorServices/Services/Analysis/AnalysisService.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointApiUtils.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/BreakpointDetails.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/DebuggerStoppedEventArgs.cs
  src/PowerShellEditorServices/Services/DebugAdapter/Debugging/StackFrameDetails.cs
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellContextFrame.cs
  src/PowerShellEditorServices/Services/PowerShell/Context/PowerShellVersionDetails.cs
  src/PowerShellEditorServices/Services/PowerShell/Runspace/SessionDetails.cs
  src/PowerShellEditorServices/Services/PowerShell/Utility/CommandHelpers.cs
  src/PowerShellEditorServices/Services/Symbols/ScriptDocumentSymbolProvider.cs
  src/PowerShellEditorServices/Services/Symbols/Vistors/AstOperations.cs
  src/PowerShellEditorServices/Services/Template/TemplateService.cs
  src/PowerShellEditorServices/Services/TextDocument/Handlers/CompletionHandler.cs
  src/PowerShellEditorServices/Services/Workspace/LanguageServerSettings.cs
  src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
  src/PowerShellEditorServices/Services/Workspace/WorkspaceService.cs
Labels: Issue-Enhancement, Area-General

#1758 With a fix in PSReadLine, we don't have to return a "null" key press
  modules.json
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-ReadLine

#1767 Release `v3.3.1`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore

#1768 Fix missed .NET 4.6.2 code
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
  src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Labels: Ignore

#1770 Update GitHub code owners
  .github/CODEOWNERS
  .poshchan/settings.json
  .vscode/snippets.code-snippets
Labels: Ignore

#1776 Don't cancel on disposal of `CancellationScope`
  src/PowerShellEditorServices/Services/PowerShell/Utility/CancellationContext.cs
Labels: Ignore

#1777 Consolidate `InterruptCurrentForeground` and `MustRunInForeground`
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/ConfigurationDoneHandler.cs
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/PowerShell/Console/PsrlReadLine.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/BlockingConcurrentDeque.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
  src/PowerShellEditorServices/Services/PowerShell/Handlers/EvaluateHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/Template/TemplateService.cs
Labels: Ignore

#1779 Update to latest PSReadLine beta (with fix for race condition)
  modules.json
Labels: Issue-Bug, Area-Integrated Console

#1778 Fix extra prompting and manual debugger commands
  src/PowerShellEditorServices/Services/DebugAdapter/Handlers/LaunchAndAttachHandler.cs
  src/PowerShellEditorServices/Services/PowerShell/Debugging/PowerShellDebugContext.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/SynchronousPowerShellTask.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Debugging

#1782 Fix ordering of startup tasks so `psEditor` is defined before profiles are loaded
  src/PowerShellEditorServices/Services/Extension/ExtensionService.cs
  src/PowerShellEditorServices/Services/PowerShell/Execution/ExecutionOptions.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  src/PowerShellEditorServices/Services/Workspace/Handlers/ConfigurationHandler.cs
  src/PowerShellEditorServices/Services/Workspace/RemoteFileManagerService.cs
Labels: Issue-Bug, Area-Startup

#1783 Release `v3.3.2`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore
