Repository PowerShell/PowerShellEditorServices, pull requests merged in 2023-04, with the labels that each got.

#2011 Add Git mailmap for Andy Jordan
  .mailmap
Labels: Ignore

#2016 Add guide to configure Neovim
  docs/guide/getting_started.md
Labels: Issue-Enhancement, Area-Documentation

#2017 Fix Dependabot pull requests limit
  .github/dependabot.yml
Labels: Ignore

#2018 Set session failure with reason when applicable
  src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
  src/PowerShellEditorServices.Hosting/Configuration/SessionFileWriter.cs
  src/PowerShellEditorServices.Hosting/EditorServicesLoader.cs
Labels: Issue-Bug, Area-Startup

#2019 Release `v3.8.4`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore
