Repository PowerShell/PowerShellEditorServices, pull requests merged in 2023-01, with the labels that each got.

#1981 Make `Set-ScriptExtent` not slow
  module/PowerShellEditorServices/Commands/Public/Set-ScriptExtent.ps1
Labels: Issue-Enhancement, Area-API

#1982 Update VS Code shell integration script
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
Labels: Issue-Bug, Area-Engine

#1983 Release `v3.7.3`
  CHANGELOG.md
  PowerShellEditorServices.Common.props
  module/PowerShellEditorServices/PowerShellEditorServices.psd1
Labels: Ignore
