Repository PowerShell/PowerShellEditorServices, pull requests merged in 2024-02, with the labels that each got.

#2115 Added null check to `GetCompletionsAsync`
  PowerShellEditorServices.build.ps1
  src/PowerShellEditorServices/Services/Symbols/Visitors/AstOperations.cs
Labels: Issue-Bug, Area-IntelliSense

#2135 Fix PowerShell 7.2 E2E unit test for last change
  test/PowerShellEditorServices.Test.E2E/LanguageServerProtocolMessageTests.cs
Labels: Issue-Bug

#2122 Add `UseNullPSHostUI` config so apps hosting PSES can disable it
  src/PowerShellEditorServices.Hosting/Commands/StartEditorServicesCommand.cs
  src/PowerShellEditorServices.Hosting/Configuration/EditorServicesConfig.cs
  src/PowerShellEditorServices.Hosting/Internal/EditorServicesRunner.cs
  src/PowerShellEditorServices/Hosting/HostStartupInfo.cs
  src/PowerShellEditorServices/Services/Analysis/PssaCmdletAnalysisEngine.cs
  src/PowerShellEditorServices/Services/PowerShell/Host/PsesInternalHost.cs
  test/PowerShellEditorServices.Test/PsesHostFactory.cs
  test/PowerShellEditorServices.Test/Services/Symbols/PSScriptAnalyzerTests.cs
Labels: Issue-Enhancement

#2138 Fixed sln file
  PowerShellEditorServices.sln
Labels: Issue-Enhancement, Area-Build & Release
